<div class="page-actions">
    <div class="page-actions-inner">
        <div class="page-actions-buttons">
            <button
                    class="action-primary"
                    title="<?php echo __('New Movie')?>"
                    onclick="setLocation('http://localhost/test/admin_pxnnwo/magenest/movietable/new')">
                <?php echo __('New Movie') ?>
            </button>
        </div>
    </div>
</div>


